services:
  - type: web
    name: ai-interview-backend
    runtime: docker
    envVars:
      - key: SPRING_DATASOURCE_URL
        # This builds the exact string Spring Boot needs
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - key: DB_HOST
        fromDatabase:
          name: ai-interview-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ai-interview-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ai-interview-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ai-in                                                                                                                                                                                                                                                                                                                                                                                    terview-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ai-interview-db
          property: password
      # Ensure your AI and Payment keys are also mapped
      - key: GEMINI_API_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: ai-interview-db
    plan: free
    databaseName: mockinterview_db
    user: admin