# ===============================
# Server Configuration
# ===============================
server.port=8081

# ===============================
# Application Name
# ===============================
spring.application.name=ai_interview

# ===============================
# Database Configuration (PostgreSQL)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mockinterview_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false


# Hibernate / JPA
# Use 'validate' or 'none' in production
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Redis Configuration (For Rate Limiting)
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# AI Configuration (Gemini)
# ===============================
# Set GEMINI_API_KEY in your IDE environment variables or OS
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.0-flash
spring.ai.google.genai.chat.options.temperature=0.7

# RSA Key Paths (Place these in src/main/resources/certs/)
app.jwt.private-key-path=certs/private_key.pem
app.jwt.public-key-path=certs/public_key.pem

# ===============================
# Email Configuration (SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dev.aiinterview@gmail.com
spring.mail.password=xtgf dhtu nhze vaji
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# Custom JWT Configuration
# ===============================
# 256-bit Hex encoded secret key
app.jwt.secret=${JWT_SECRET}

# Token expiration in milliseconds (24 hours)
app.jwt.expiration-ms=86400000


# Enable Java 21 Virtual Threads (Project Loom)
spring.threads.virtual.enabled=true

#paystack secret key
paystack.secret.key=${PAYSTACK_SECRET_KEY}