### 1. Register a New User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Wick",
  "email": "john.wick@continental.com",
  "password": "guns.lots.of.guns"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
    // Save the token automatically to a variable named 'auth_token'
    client.global.set("auth_token", response.body.token);
%}

###

### 2. Login (Get Token)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "john.wick@continental.com",
  "password": "guns.lots.of.guns"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    // Update the token variable
    client.global.set("auth_token", response.body.token);
%}

###

### 3. Get My Profile (Protected Endpoint)
GET http://localhost:8080/api/v1/users/profile
Authorization: Bearer {{auth_token}}
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.email === "john.wick@continental.com", "Email does not match!");
    });
%}