-- Flyway baseline migration: Add performance index for interview sessions (Moved to JPA Entity annotations)
-- CREATE INDEX IF NOT EXISTS idx_interview_sessions_user ON interview_sessions (user_id);
